[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "fluidity"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "net",
    "tokio"
]
full = ["net"]
net = [
    "fluidity-net"
]


[lib]
bench = true
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dependencies]
# SDK
fluidity-net = { features = [], optional = true, path = "../network/net", version = "0.1.12" }

chrono = "0.4"
serde.workspace = true
serde_json.workspace = true
tokio = { features = ["macros"], optional = true, version = "1" }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown.dependencies]
gloo = { features = ["futures"], version = "0.8" }
js-sys = "0.3"
wasm-bindgen = { features = ["serde-serialize"], version = "0.2" }
wasm-bindgen-futures = "0.4"

[target.wasm32-unknown-unknown.dependencies.web-sys]
features = [
    "HtmlElement",
    "Node"
]
version = "0.3"

[target.wasm32-unknown-unknown.dev-dependencies]
wasm-bindgen-test = "0.3"

[target.wasm32-wasi.dependencies]
tokio_wasi = { features = ["macros"], version = "1"}