version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /crates/sdk
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /fluidity
    schedule:
      interval: daily
