version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /cargo/api
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /cargo/cli
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /lib/fluidity
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /lib/core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /lib/derive
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /lib/macros
    schedule:
      interval: daily