[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "Flow is a complete digital identity management toolkit"
edition = "2021"
homepage = "https://scattered-systems.github.io/flow"
keywords = ["blockchain", "digital identity", "management"]
license = "MIT"
name = "flow"
readme = "https://gitlab.com/scsys/flow/flow/#README"
repository = "https://gitlab.com/scsys/flow/flow"
version = "0.1.0"

[[bin]]
bench = false
name = "flow"

[build-dependencies]

[dependencies]
clap = { features = ["derive"], version = "4.0.8" }
ethers = "0.17.0"
opentelemetry = "0.18.0"
reqwest = { features = ["stream"], version = "0.11.12" }
scsys = { features = ["full"], version = "0.1.18" }
serde = { default-features = false, features = ["derive"], version = "1.0.145" }
serde_json = "1.0.85"
strum = { features = ["derive"], version = "0.24.1" }
tarpc = "0.30.0"
tokio = { features = ["full"], version = "1.21.2" }
tokio-stream = "0.1.10"
tower = "0.4.13"
tower-cookies = "0.7.0"
tower-http = { features = ["full"], version = "0.3.4" }
tracing = "0.1.36"
tracing-subscriber = { features = ["env-filter"], version = "0.3.15" }

[dev-dependencies]

