[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "Flow"
edition = "2021"
homepage = "https://github.com/scattered-systems/flow/wiki"
keywords = ["blockchain", "digital identity", "management"]
license = "Apache-2.0"
name = "flow"
repository = "https://github.com/scattered-systems/flow"
version = "0.1.12"

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dev-dependencies]
wasm-bindgen-test = "0.3"

[dependencies]
gloo = { features = ["futures"], version = "0.8.0" }
js-sys = "0.3.60"
serde = { features = ["derive"], version = "1" }
serde_json = "1"
tokio = { features = ["macros"], version = "1.23.0" }
wasm-bindgen = { features = ["serde-serialize"], version = "0.2.83" }
wasm-bindgen-futures = "0.4.33"

fluidity = { features = [], path = "../crates/fluidity", version = "0.1.12"}

[dependencies.web-sys]
features = [
    "Client"
]
version = "0.3.60"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
