[package]
authors.workspace = true
categories.workspace = true
default-run = "flow"
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "flow"
readme.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
bench = true
doctest = false
name = "flow"

[build-dependencies]

[dependencies]
# SDK
fluidity = { features = [], path = "../crates/fluidity", version = "0.1.12" }

serde.workspace = true
serde_json.workspace = true
tokio = { features = ["full"], version = "1" }


[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
