[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems <jo3mccain@scattered-systems.com>"]
description = "Enabling users to quickly adapt to any environment with a complete DiD Toolkit"
edition = "2021"
license = "MIT"
name = "flow"
repository = "https://github.com/scattered-systems/flow.git"
version = "0.1.0"

[[bin]]
bench = false
test = false

[dependencies]
acme = "0.1.1"
axum = { features = ["headers"], version = "0.5.6" }
bcrypt = "0.13.0"
bson = { features = ["chrono-0_4", "serde_with"], version = "2.2.0" }
chrono = "0.4.19"
config = "0.13.1"
fluidity = "0.1.0"
hyper = { features = ["full"], version = "0.14.18" }
serde = { features = ["derive"], version = "1.0.137" }
serde_json = "1.0.81"
tokio = { features = ["full"], version = "1.18.2" }
tower = "0.4.12"