[package]
authors = []
categories = []
edition = "2021"
homepage = ""
keywords = []
license = "Apache-2.0"
name = "flow-xtask"
version = "0.1.0"

[dependencies]
clap = { feature = ["derive"], version = "4.0.29" }
duct = "0.13.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
wild = "2.1.0"
