[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
categories = []
description = "Flow is a complete digital identity platform"
edition = "2021"
homepage = "https://github.com/scattered-systems/flow"
keywords = []
name = "flow"
readme = "README.md"
repository = "https://github.com/scattered-systems/flow"
version = "0.1.0"

[[bin]]
bench = false
name = "flow"

[dependencies]

[dev-dependencies]

[build-dependencies]

