[package]
authors = [
    "FL03 <jo3mccain@icloud.com> (https://github.com/FL03)",
    "Scattered-Systems (https://github.com/scattered-systems)"
]
categories = []
description = "Flow is a complete digital identity platform"
edition = "2021"
homepage = "https://scattered-systems.github.io/flow/"
keywords = []
license = "MIT"
name = "flow-cli"
repository = "https://github.com/scattered-systems/flow"
version = "0.1.0"

[[bin]]
bench = false
name = "flow-cli"
test = false

[build-dependencies]

[dependencies]
clap = { features = ["derive"], version = "3.2.12" }
futures = "0.3.21"
serde = { features = ["derive"], version = "1.0.140" }
serde_json = "1.0.82"
tokio = { features = ["full"], version = "1.20.1" }

[dependencies.acme]
features = ["full"]
version = "0.2.0"

[dependencies.fluidity]
features = ["full"]
path = "../../lib/fluidity"

[dependencies.scsys]
features = ["full"]
version = "0.1.11"

[dev-dependencies]
