[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
categories = []
description = "Flow is a complete digital identity platform"
edition = "2021"
homepage = "https://scattered-systems.github.io/flow/"
keywords = []
license = "MIT"
name = "flow-cli"
repository = "https://github.com/scattered-systems/flow"
version = "0.1.0"

[[bin]]
bench = false
name = "flow-cli"
test = false

[build-dependencies]

[dependencies]
bson = { features = ["chrono-0_4", "serde_with"], version = "2.3.0" }
chrono = "0.4.19"
clap = { features = ["derive"], version = "3.2.12" }
config = "0.13.1"
digest = "0.10.3"
futures = "0.3.21"
glob = "0.3.0"
serde = { features = ["derive"], version = "1.0.140" }
serde_json = "1.0.82"

[dependencies.fluidity]
optional = false
path = "../../lib/fluidity"
version = "0.1.5"

[dependencies.scsys]
features = ["full"]
optional = false
version = "0.1.7"

[dev-dependencies]
