[application]
mode = "development"
name = "rs-sandbox"

[database]
name = "postgres"
uri = "postgres://postgres:example@localhost:5432/postgres"

[logger]
level = "debug"

[server]
host = "0.0.0.0"
port = 8080