[application]
mode = "development"
name = "Flow"

[logger]
level = "debug"

[cache]
name = "redis"
uri = "redis://localhost:6379"

[database]
name = "sqlite"
uri = "sqlite://:memory:"

[ethereum]
name = "ethereum"
url = "https://rpc.ankr.com/eth"

[server]
host = "0.0.0.0"
port = 9000