name: Crates

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ created ]
  repository_dispatch:
    types: [ publish ]
  workflow_dispatch:

jobs:
  sdk:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-sdk
      cancel-in-progress: false
    env:
        SDK_NAME: fluidity
    name: Publish (sdk)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [ core ]
        sdk: [ fluidity ]
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ matrix.sdk }}-${{ matrix.features }})
        run: cargo publish --all-features -v -p ${{ matrix.sdk }}-${{ matrix.features }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  
  publish:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-publish
      cancel-in-progress: false
    name: Publish (bin)
    needs: sdk
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin: [ "flow" ]
    steps:
      - uses: actions/checkout@v4
      - name: Publish (bin)
        run: cargo publish --all-features -v -p flow --token ${{ secrets.CARGO_REGISTRY_TOKEN }}