name: Crates

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

on:
  push:
    tags: [ "nightly*",  "v*.*.*" ]
  release:
    types: [ "created" ]
  repository_dispatch:
    types: [ "publish" ]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup (langspace)
        run: |
          rustup update
          rustup default nightly
      - id: rust-build
        name: Build
        run: cargo build -r -v --workspace
      - uses: actions/cache@v2
        id: rust-cache
        name: Cache build
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  sdk:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-sdk
      cancel-in-progress: false
    env:
        SDK_NAME: fluidity
    name: Publish (sdk)
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [ "core", "minis", "net" ]
        sdk: [ "fluidity" ]
    steps:
      - uses: actions/checkout@v3
      - name: Publish (${{ matrix.sdk }}-${{ matrix.features }})
        run: cargo publish --all-features -v -p ${{ matrix.sdk }}-${{ matrix.features }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  
  publish:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-publish
      cancel-in-progress: false
    name: Publish (bin)
    needs: sdk
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin: [ "flow" ]
    steps:
      - uses: actions/checkout@v3
      - name: Publish (bin)
        run: cargo publish --all-features -v -p flow --token ${{ secrets.CARGO_REGISTRY_TOKEN }}