name: Rust

on:
  schedule:
    - cron: "30 21 * * *" # 9:30pm UTC

jobs:
  rust:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
        toolchain: [ nightly ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: build (${{ matrix.toolchain }}) (${{ matrix.platform }})
        run: cargo build --release --workspace -v
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nightly-flow-${{ matrix.platform }}
          path: target/release/flow
      - name: release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              body: 'View the assets bundled below to find a suitable installer for your host system',
              configPath: 'Flow.toml',
              draft: false,
              name: `Flow nightly-v${process.env.CARGO_PKG_VERSION}`,
              owner: context.repo.owner,
              prerelease: true,
              repo: context.repo.repo,
              tag_name: `nightly-v${process.env.CARGO_PKG_VERSION}`
            })
            return data.id