name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: cargo login ${CARGO_REGISTRY_TOKEN}
    - name: Build
      run: cargo build --verbose --workspace
    - name: Cache
      uses: actions/cache@v3.0.11
      with:
        path: "/target/release"
        key: "build"
    - name: Run tests
      run: cargo test --all --verbose
#     - name: Publish
#       run: |
#         cargo publish
#       if: github.event_name == 'push'
