name: Rust

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ main ]
    tags: [ nightly*,  v*.*.* ]
  release:
  repository_dispatch:
    types: [ publish ]
  schedule:
    - cron: "30 21 * * 0" # Every Sunday at 9:30pm UTC
  workflow_dispatch:
    inputs:
      bench:
        description: "Run benchmarks"
        required: false
        default: false
        type: boolean
      platform:
        description: "Platform to run the build on"
        required: true
        default: "ubuntu-latest"
        type: string
      toolchain:
        description: "Rust toolchain to use"
        required: true
        default: "nightly"
        type: string

jobs:
  builder:
    name: Build
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        toolchain: [ stable, nightly ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup (langspace)
        run: |
          rustup update
          rustup default ${{ matrix.toolchain }}
      - name: Build
        id: rust-build
        run: cargo build --features full -r -v --workspace
      - name: Cache build
        id: rust-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/release
          key: ${{ matrix.toolchain }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  test:
    name: Test
    needs: builder
    strategy:
      matrix:
        toolchain: [ stable, nightly ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup (langspace)
        run: |
          rustup update
          rustup default ${{ matrix.toolchain }}
      - name: Test
        id: rust-test
        run: cargo test --features full -v --workspace
  benchmark:
    name: Benchmark
    needs: builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup (langspace)
        run: |
          rustup update
          rustup default nightly
      - name: Bench
        id: rust-bench
        run: cargo bench --features full -v --workspace