name: Rust

on:
  push:
    branches:
      - latest
    tags:
      - v*.*.*
  pull_request:
    branches:
      - latest
    tags:
      - v*.*.*

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --all-features --color always --release --verbose
  core:
    env:
      CRATE: fluidity-core
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --all-features
  derive:
    env:
      CRATE: fluidity-derive
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --all-features
  macros:
    env:
      CRATE: fluidity-macros
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --all-features
  crate:
    env:
      CRATE: fluidity
    needs: [ core, derive, login, macros, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CRATE --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --all-features