name: Rust

on:
  push:
    branches-ignore: [ "dev*", "next*" ]
    tags: [ "beta*", "nightly*", "prod*", "v*.*.*"]
  pull_request:
    branches-ignore: [ "dev*", "next*" ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo login ${CARGO_REGISTRY_TOKEN}
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
        toolchain: [ nightly, stable ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: build (${{ matrix.toolchain }})
      run: cargo build --release --workspace -v
    - name: Cache
      uses: actions/cache@v3
      with:
        path: "/target/release/flow"
        key: "build"
    - uses: actions/upload-artifact@v2
      with:
        name: flow-${{ matrix.platform }}
        path: target/release/flow
    - uses: actions/upload-artifact@v2
      with:
        name: fluidity-${{ matrix.platform }}
        path: target/release/fluidity
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
        toolchain: [ nightly, stable ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Test (${{ matrix.toolchain }})
      run: cargo test --all --all-features --color ${CARGO_TERM_COLOR} --release -v
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --release -v --workspace
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: bundle
          path: /target/release/flow
      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          path: "/target/release/flow"
          key: "build"
      - name: release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              body: 'View the assets bundled below to find a suitable installer for your host system',
              configPath: 'Flow.toml',
              draft: false,
              name: `Flow v${process.env.PACKAGE_VERSION}`,
              owner: context.repo.owner,
              prerelease: true,
              repo: context.repo.repo,
              tag_name: `beta-v${process.env.PACKAGE_VERSION}`
            })
            return data.id
